import type { Produit, Recette } from './types'

// --- Référentiel produits (générique, partagé) -----------------------------
// p(id, nom, rayon, type, kcal/100, périssable)
function p(
  id: string,
  nom: string,
  rayon: Produit['rayon'],
  type: Produit['type'],
  kcal100: number | null,
  perissable = false,
): Produit {
  return { id, nom, rayon, type, kcal100, perissable }
}

export const PRODUITS_SEED: Produit[] = [
  p('pates', 'Pâtes', 'epicerie', 'packaged', 350),
  p('riz', 'Riz', 'epicerie', 'packaged', 350),
  p('semoule', 'Semoule', 'epicerie', 'packaged', 360),
  p('lentilles', 'Lentilles', 'epicerie', 'packaged', 340),
  p('farine', 'Farine', 'epicerie', 'packaged', 360),
  p('sucre', 'Sucre', 'epicerie', 'packaged', 400),
  p('huile', "Huile d'olive", 'epicerie', 'packaged', 900),
  p('sauce-tomate', 'Sauce tomate', 'epicerie', 'packaged', 60),
  p('thon', 'Thon en boîte', 'epicerie', 'packaged', 130),
  p('mais', 'Maïs en boîte', 'epicerie', 'packaged', 90),
  p('haricots-verts', 'Haricots verts', 'epicerie', 'packaged', 35),
  p('pois-chiches', 'Pois chiches', 'epicerie', 'packaged', 160),
  p('pate-brisee', 'Pâte brisée', 'epicerie', 'packaged', 360, true),
  p('lardons', 'Lardons', 'viande-poisson', 'packaged', 310, true),
  p('poulet', 'Filet de poulet', 'viande-poisson', 'frais', 165, true),
  p('boeuf-hache', 'Bœuf haché', 'viande-poisson', 'frais', 250, true),
  p('jambon', 'Jambon', 'viande-poisson', 'packaged', 110, true),
  p('saucisse', 'Saucisse', 'viande-poisson', 'frais', 300, true),
  p('poisson-pane', 'Poisson pané', 'surgele', 'packaged', 200),
  p('petit-pois', 'Petits pois', 'surgele', 'packaged', 80),
  p('oeuf', 'Œufs', 'cremerie', 'frais', 140, true),
  p('lait', 'Lait', 'cremerie', 'packaged', 47, true),
  p('creme', 'Crème fraîche', 'cremerie', 'packaged', 290, true),
  p('beurre', 'Beurre', 'cremerie', 'packaged', 740, true),
  p('fromage-rape', 'Fromage râpé', 'cremerie', 'packaged', 350, true),
  p('yaourt', 'Yaourt', 'cremerie', 'frais', 60, true),
  p('pomme-de-terre', 'Pommes de terre', 'fruits-legumes', 'frais', 80, true),
  p('carotte', 'Carottes', 'fruits-legumes', 'frais', 40, true),
  p('oignon', 'Oignon', 'fruits-legumes', 'frais', 40, true),
  p('ail', 'Ail', 'fruits-legumes', 'frais', 130, true),
  p('tomate', 'Tomates', 'fruits-legumes', 'frais', 20, true),
  p('courgette', 'Courgette', 'fruits-legumes', 'frais', 17, true),
  p('salade', 'Salade verte', 'fruits-legumes', 'frais', 15, true),
  p('banane', 'Banane', 'fruits-legumes', 'frais', 90, true),
  p('pomme', 'Pomme', 'fruits-legumes', 'frais', 52, true),
  p('pain', 'Pain de mie', 'boulangerie', 'packaged', 270, true),
  // --- produits ajoutés (petits-déj, recettes du monde…) ---
  p('flocons-avoine', "Flocons d'avoine", 'epicerie', 'packaged', 370),
  p('miel', 'Miel', 'epicerie', 'packaged', 300),
  p('confiture', 'Confiture', 'epicerie', 'packaged', 270),
  p('fromage-blanc', 'Fromage blanc', 'cremerie', 'frais', 75, true),
  p('cereales', 'Céréales', 'epicerie', 'packaged', 380),
  p('chocolat', 'Chocolat', 'epicerie', 'packaged', 540),
  p('avocat', 'Avocat', 'fruits-legumes', 'frais', 160, true),
  p('saumon', 'Saumon', 'viande-poisson', 'frais', 200, true),
  p('crevettes', 'Crevettes', 'viande-poisson', 'frais', 100, true),
  p('nouilles', 'Nouilles chinoises', 'epicerie', 'packaged', 350),
  p('sauce-soja', 'Sauce soja', 'epicerie', 'packaged', 60),
  p('gnocchi', 'Gnocchi', 'epicerie', 'packaged', 160, true),
  p('mozzarella', 'Mozzarella', 'cremerie', 'packaged', 280, true),
  p('tortilla', 'Tortillas / wraps', 'boulangerie', 'packaged', 300),
  p('poivron', 'Poivron', 'fruits-legumes', 'frais', 30, true),
  p('champignon', 'Champignons', 'fruits-legumes', 'frais', 22, true),
  p('epices', 'Épices / curry', 'epicerie', 'packaged', 300),
  // substituts courants
  p('echalote', 'Échalote', 'fruits-legumes', 'frais', 40, true),
  p('poireau', 'Poireau', 'fruits-legumes', 'frais', 30, true),
  p('aubergine', 'Aubergine', 'fruits-legumes', 'frais', 25, true),
  p('brocoli', 'Brocoli', 'fruits-legumes', 'frais', 35, true),
  p('dinde', 'Escalope de dinde', 'viande-poisson', 'frais', 110, true),
]

// Substituts possibles par produit : permet de remplacer un ingrédient qu'on
// n'aime pas par un autre du même rôle (ex. Ezio n'aime pas l'oignon -> échalote).
export const SUBSTITUTS: Record<string, string[]> = {
  oignon: ['echalote', 'poireau'],
  echalote: ['oignon'],
  poireau: ['oignon', 'courgette'],
  courgette: ['aubergine', 'brocoli', 'poireau'],
  aubergine: ['courgette'],
  champignon: ['courgette', 'poivron'],
  poivron: ['courgette', 'carotte'],
  carotte: ['courgette', 'petit-pois'],
  poulet: ['dinde'],
  dinde: ['poulet'],
  lardons: ['jambon'],
  jambon: ['lardons'],
  saumon: ['poisson-pane'],
  creme: ['lait'],
  pates: ['riz', 'gnocchi'],
  riz: ['pates', 'semoule'],
  semoule: ['riz'],
}

// Poids typique d'une "pièce" (en g), pour estimer les calories même quand on
// compte à l'unité (1 œuf, 1 banane…) plutôt qu'en grammes.
export const POIDS_PIECE: Record<string, number> = {
  oeuf: 60,
  banane: 120,
  pomme: 150,
  pain: 30,
  tortilla: 60,
  avocat: 150,
  'poisson-pane': 75,
  saucisse: 80,
  yaourt: 125,
  carotte: 120,
  oignon: 110,
  echalote: 30,
  poireau: 150,
  courgette: 200,
  aubergine: 250,
  brocoli: 300,
  poivron: 150,
  tomate: 120,
  ail: 5,
  'pate-brisee': 230,
}

// Produit qui se compte à l'unité (œuf, fruit/légume, crêpe, pavé de saumon…) :
// on affiche un compteur. Le reste (farine, sel, huile…) = simple présence.
export function estComptable(p: Produit): boolean {
  if (p.rayon === 'fruits-legumes') return true
  if (POIDS_PIECE[p.id] != null || (p.canonId && POIDS_PIECE[p.canonId] != null)) return true
  return /saumon|cr[êe]pe|galette|gaufre|steak|pav[ée]|tranche|\boeufs?\b|pizza|wrap|tortilla|yaourt|escalope|filet/i.test(
    p.nom,
  )
}


// --- Recettes de départ ----------------------------------------------------
// (ingrédients liés aux produits ci-dessus, temps réels, kcal par portion estimé)

export const RECETTES_SEED: Recette[] = [
  {
    id: 'pates-lardons',
    nom: 'Pâtes aux lardons',
    emoji: '🍝',
    tempsMin: 15,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner', 'diner'],
    tags: ['rapide', 'réconfort', 'enfant'],
    ingredients: [
      { produitId: 'pates', quantite: 200, unite: 'g' },
      { produitId: 'lardons', quantite: 150, unite: 'g' },
      { produitId: 'creme', quantite: 100, unite: 'ml' },
      { produitId: 'oeuf', quantite: 1, unite: 'piece', optionnel: true },
    ],
    etapes: [
      'Faire bouillir les pâtes (10 min).',
      'Faire revenir les lardons à la poêle 5 min.',
      'Ajouter la crème, mélanger, poivrer.',
      'Égoutter les pâtes, mélanger avec la sauce. Voilà !',
    ],
    kcalPortion: 620,
    proteine: 2,
    legume: 0,
    feculent: 3,
  },
  {
    id: 'poulet-riz-haricots',
    nom: 'Poulet, riz et haricots verts',
    emoji: '🍗',
    tempsMin: 25,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner', 'diner'],
    tags: ['équilibré'],
    ingredients: [
      { produitId: 'poulet', quantite: 250, unite: 'g' },
      { produitId: 'riz', quantite: 120, unite: 'g' },
      { produitId: 'haricots-verts', quantite: 250, unite: 'g' },
      { produitId: 'huile', quantite: 1, unite: 'cas' },
    ],
    etapes: [
      'Cuire le riz selon le paquet.',
      'Couper le poulet en morceaux, le faire dorer à la poêle 10 min.',
      'Réchauffer les haricots verts.',
      'Servir le tout ensemble.',
    ],
    kcalPortion: 480,
    proteine: 3,
    legume: 2,
    feculent: 2,
  },
  {
    id: 'omelette',
    nom: 'Omelette',
    emoji: '🍳',
    tempsMin: 10,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner', 'diner'],
    tags: ['rapide', 'végé'],
    ingredients: [
      { produitId: 'oeuf', quantite: 4, unite: 'piece' },
      { produitId: 'beurre', quantite: 10, unite: 'g' },
      { produitId: 'fromage-rape', quantite: 40, unite: 'g', optionnel: true },
    ],
    etapes: [
      'Battre les œufs, saler, poivrer.',
      'Faire fondre le beurre à la poêle.',
      'Verser les œufs, ajouter le fromage, plier quand c’est pris.',
    ],
    kcalPortion: 320,
    proteine: 3,
    legume: 0,
    feculent: 0,
  },
  {
    id: 'riz-cantonais',
    nom: 'Riz cantonais express',
    emoji: '🍚',
    tempsMin: 20,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner', 'diner'],
    tags: ['enfant', 'rapide'],
    ingredients: [
      { produitId: 'riz', quantite: 150, unite: 'g' },
      { produitId: 'oeuf', quantite: 2, unite: 'piece' },
      { produitId: 'jambon', quantite: 100, unite: 'g' },
      { produitId: 'petit-pois', quantite: 100, unite: 'g' },
    ],
    etapes: [
      'Cuire le riz, le laisser tiédir.',
      'Faire une omelette, la couper en lamelles.',
      'Faire sauter riz, jambon coupé, petits pois et œuf 5 min.',
    ],
    kcalPortion: 430,
    proteine: 2,
    legume: 1,
    feculent: 3,
  },
  {
    id: 'gratin-pates',
    nom: 'Gratin de pâtes jambon-fromage',
    emoji: '🧀',
    tempsMin: 30,
    portions: 3,
    difficulte: 2,
    moments: ['diner'],
    tags: ['réconfort', 'enfant'],
    ingredients: [
      { produitId: 'pates', quantite: 300, unite: 'g' },
      { produitId: 'jambon', quantite: 150, unite: 'g' },
      { produitId: 'fromage-rape', quantite: 100, unite: 'g' },
      { produitId: 'creme', quantite: 150, unite: 'ml' },
      { produitId: 'lait', quantite: 100, unite: 'ml' },
    ],
    etapes: [
      'Cuire les pâtes al dente.',
      'Mélanger pâtes, jambon, crème, lait dans un plat.',
      'Couvrir de fromage, four 15 min à 200°C.',
    ],
    kcalPortion: 560,
    proteine: 2,
    legume: 0,
    feculent: 3,
  },
  {
    id: 'steak-puree',
    nom: 'Steak haché et purée',
    emoji: '🥔',
    tempsMin: 25,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner', 'diner'],
    tags: ['enfant', 'réconfort'],
    ingredients: [
      { produitId: 'boeuf-hache', quantite: 250, unite: 'g' },
      { produitId: 'pomme-de-terre', quantite: 400, unite: 'g' },
      { produitId: 'lait', quantite: 80, unite: 'ml' },
      { produitId: 'beurre', quantite: 20, unite: 'g' },
    ],
    etapes: [
      'Cuire les pommes de terre à l’eau 20 min.',
      'Écraser avec le lait et le beurre.',
      'Cuire les steaks 3 min par face.',
    ],
    kcalPortion: 520,
    proteine: 3,
    legume: 0,
    feculent: 2,
  },
  {
    id: 'bolo',
    nom: 'Spaghetti bolognaise',
    emoji: '🍝',
    tempsMin: 35,
    portions: 3,
    difficulte: 2,
    moments: ['dejeuner', 'diner'],
    tags: ['équilibré', 'enfant'],
    ingredients: [
      { produitId: 'pates', quantite: 300, unite: 'g' },
      { produitId: 'boeuf-hache', quantite: 300, unite: 'g' },
      { produitId: 'sauce-tomate', quantite: 200, unite: 'ml' },
      { produitId: 'oignon', quantite: 1, unite: 'piece' },
      { produitId: 'carotte', quantite: 1, unite: 'piece', optionnel: true },
    ],
    etapes: [
      'Émincer oignon et carotte, faire revenir.',
      'Ajouter la viande, faire dorer.',
      'Verser la sauce tomate, mijoter 15 min.',
      'Servir sur les pâtes cuites.',
    ],
    kcalPortion: 540,
    proteine: 3,
    legume: 1,
    feculent: 3,
  },
  {
    id: 'salade-thon',
    nom: 'Salade thon-maïs',
    emoji: '🥗',
    tempsMin: 10,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner'],
    tags: ['rapide', 'équilibré', 'été'],
    ingredients: [
      { produitId: 'salade', quantite: 150, unite: 'g' },
      { produitId: 'thon', quantite: 120, unite: 'g' },
      { produitId: 'mais', quantite: 150, unite: 'g' },
      { produitId: 'oeuf', quantite: 2, unite: 'piece', optionnel: true },
    ],
    etapes: [
      'Laver et couper la salade.',
      'Ajouter thon égoutté, maïs, œufs durs.',
      'Assaisonner.',
    ],
    kcalPortion: 290,
    proteine: 2,
    legume: 2,
    feculent: 1,
  },
  {
    id: 'soupe-legumes',
    nom: 'Soupe de légumes',
    emoji: '🥕',
    tempsMin: 30,
    portions: 3,
    difficulte: 1,
    moments: ['diner'],
    tags: ['équilibré', 'végé', 'réconfort'],
    ingredients: [
      { produitId: 'pomme-de-terre', quantite: 300, unite: 'g' },
      { produitId: 'carotte', quantite: 2, unite: 'piece' },
      { produitId: 'courgette', quantite: 1, unite: 'piece' },
      { produitId: 'oignon', quantite: 1, unite: 'piece' },
    ],
    etapes: [
      'Éplucher et couper les légumes.',
      'Couvrir d’eau, cuire 25 min.',
      'Mixer, saler.',
    ],
    kcalPortion: 180,
    proteine: 0,
    legume: 3,
    feculent: 1,
  },
  {
    id: 'croque',
    nom: 'Croque-monsieur',
    emoji: '🥪',
    tempsMin: 12,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner', 'diner'],
    tags: ['rapide', 'enfant'],
    ingredients: [
      { produitId: 'pain', quantite: 4, unite: 'piece' },
      { produitId: 'jambon', quantite: 100, unite: 'g' },
      { produitId: 'fromage-rape', quantite: 80, unite: 'g' },
      { produitId: 'beurre', quantite: 15, unite: 'g' },
    ],
    etapes: [
      'Beurrer le pain.',
      'Garnir de jambon et fromage.',
      'Cuire au four ou à la poêle 6 min.',
    ],
    kcalPortion: 410,
    proteine: 2,
    legume: 0,
    feculent: 2,
  },
  {
    id: 'poisson-pane-pois',
    nom: 'Poisson pané et petits pois',
    emoji: '🐟',
    tempsMin: 20,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner', 'diner'],
    tags: ['enfant', 'rapide'],
    ingredients: [
      { produitId: 'poisson-pane', quantite: 2, unite: 'piece' },
      { produitId: 'petit-pois', quantite: 200, unite: 'g' },
      { produitId: 'pomme-de-terre', quantite: 200, unite: 'g', optionnel: true },
    ],
    etapes: [
      'Cuire le poisson pané au four 15 min.',
      'Réchauffer les petits pois.',
      'Servir.',
    ],
    kcalPortion: 380,
    proteine: 2,
    legume: 1,
    feculent: 2,
  },
  {
    id: 'quiche',
    nom: 'Quiche lorraine',
    emoji: '🥧',
    tempsMin: 40,
    portions: 4,
    difficulte: 2,
    moments: ['dejeuner', 'diner'],
    tags: ['réconfort'],
    ingredients: [
      { produitId: 'pate-brisee', quantite: 1, unite: 'piece' },
      { produitId: 'oeuf', quantite: 3, unite: 'piece' },
      { produitId: 'creme', quantite: 200, unite: 'ml' },
      { produitId: 'lardons', quantite: 200, unite: 'g' },
    ],
    etapes: [
      'Étaler la pâte dans un moule.',
      'Battre œufs et crème, ajouter les lardons.',
      'Verser, cuire 30 min à 200°C.',
    ],
    kcalPortion: 470,
    proteine: 2,
    legume: 0,
    feculent: 2,
  },
  {
    id: 'crepes',
    nom: 'Crêpes',
    emoji: '🥞',
    tempsMin: 25,
    portions: 4,
    difficulte: 2,
    moments: ['diner', 'gouter', 'dessert'],
    tags: ['enfant', 'réconfort'],
    ingredients: [
      { produitId: 'farine', quantite: 250, unite: 'g' },
      { produitId: 'oeuf', quantite: 3, unite: 'piece' },
      { produitId: 'lait', quantite: 500, unite: 'ml' },
      { produitId: 'sucre', quantite: 30, unite: 'g' },
      { produitId: 'beurre', quantite: 20, unite: 'g' },
    ],
    etapes: [
      'Mélanger farine, œufs, lait, sucre.',
      'Laisser reposer 30 min si possible.',
      'Cuire à la poêle beurrée.',
    ],
    kcalPortion: 350,
    proteine: 1,
    legume: 0,
    feculent: 3,
  },
  {
    id: 'couscous-vege',
    nom: 'Couscous express végé',
    emoji: '🥘',
    tempsMin: 30,
    portions: 3,
    difficulte: 2,
    moments: ['dejeuner', 'diner'],
    tags: ['végé', 'équilibré'],
    ingredients: [
      { produitId: 'semoule', quantite: 200, unite: 'g' },
      { produitId: 'pois-chiches', quantite: 250, unite: 'g' },
      { produitId: 'courgette', quantite: 1, unite: 'piece' },
      { produitId: 'carotte', quantite: 2, unite: 'piece' },
      { produitId: 'oignon', quantite: 1, unite: 'piece' },
    ],
    etapes: [
      'Couper les légumes, les faire mijoter 20 min.',
      'Préparer la semoule (eau bouillante + couvrir 5 min).',
      'Ajouter les pois chiches, servir sur la semoule.',
    ],
    kcalPortion: 410,
    proteine: 2,
    legume: 3,
    feculent: 3,
  },
  {
    id: 'pates-tomate',
    nom: 'Pâtes sauce tomate',
    emoji: '🍅',
    tempsMin: 15,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner', 'diner'],
    tags: ['rapide', 'végé', 'enfant'],
    ingredients: [
      { produitId: 'pates', quantite: 200, unite: 'g' },
      { produitId: 'sauce-tomate', quantite: 200, unite: 'ml' },
      { produitId: 'fromage-rape', quantite: 50, unite: 'g', optionnel: true },
    ],
    etapes: [
      'Cuire les pâtes.',
      'Réchauffer la sauce tomate.',
      'Mélanger, parsemer de fromage.',
    ],
    kcalPortion: 420,
    proteine: 1,
    legume: 1,
    feculent: 3,
  },
  {
    id: 'lentilles-saucisses',
    nom: 'Lentilles et saucisses',
    emoji: '🫘',
    tempsMin: 40,
    portions: 3,
    difficulte: 2,
    moments: ['dejeuner', 'diner'],
    tags: ['réconfort', 'équilibré'],
    ingredients: [
      { produitId: 'lentilles', quantite: 250, unite: 'g' },
      { produitId: 'saucisse', quantite: 3, unite: 'piece' },
      { produitId: 'carotte', quantite: 2, unite: 'piece' },
      { produitId: 'oignon', quantite: 1, unite: 'piece' },
    ],
    etapes: [
      'Faire revenir oignon et carotte.',
      'Ajouter les lentilles et de l’eau, cuire 25 min.',
      'Cuire les saucisses à part, servir ensemble.',
    ],
    kcalPortion: 490,
    proteine: 3,
    legume: 1,
    feculent: 2,
  },
  {
    id: 'yaourt-banane',
    nom: 'Yaourt banane',
    emoji: '🍌',
    tempsMin: 5,
    portions: 1,
    difficulte: 1,
    moments: ['gouter', 'dessert', 'petit-dej'],
    tags: ['rapide', 'enfant', 'sucré'],
    ingredients: [
      { produitId: 'yaourt', quantite: 1, unite: 'piece' },
      { produitId: 'banane', quantite: 1, unite: 'piece' },
    ],
    etapes: ['Couper la banane.', 'Mélanger au yaourt. Miam.'],
    kcalPortion: 160,
    proteine: 1,
    legume: 0,
    feculent: 1,
  },

  // ===== Petits-déjeuners =====
  {
    id: 'porridge-banane',
    nom: 'Porridge banane',
    emoji: '🥣',
    tempsMin: 8,
    portions: 1,
    difficulte: 1,
    moments: ['petit-dej'],
    tags: ['rapide', 'sucré', 'équilibré'],
    ingredients: [
      { produitId: 'flocons-avoine', quantite: 60, unite: 'g' },
      { produitId: 'lait', quantite: 200, unite: 'ml' },
      { produitId: 'banane', quantite: 1, unite: 'piece' },
      { produitId: 'miel', quantite: 1, unite: 'cac', optionnel: true },
    ],
    etapes: [
      'Chauffer flocons + lait 4 min en remuant.',
      'Ajouter la banane en rondelles et un peu de miel.',
    ],
    kcalPortion: 320,
    proteine: 1,
    legume: 0,
    feculent: 3,
  },
  {
    id: 'tartines-confiture',
    nom: 'Tartines beurre-confiture',
    emoji: '🍞',
    tempsMin: 5,
    portions: 1,
    difficulte: 1,
    moments: ['petit-dej', 'gouter'],
    tags: ['rapide', 'sucré', 'enfant'],
    ingredients: [
      { produitId: 'pain', quantite: 2, unite: 'piece' },
      { produitId: 'beurre', quantite: 15, unite: 'g' },
      { produitId: 'confiture', quantite: 30, unite: 'g' },
    ],
    etapes: ['Toaster le pain.', 'Tartiner beurre puis confiture.'],
    kcalPortion: 290,
    proteine: 0,
    legume: 0,
    feculent: 2,
  },
  {
    id: 'oeufs-brouilles',
    nom: 'Œufs brouillés',
    emoji: '🍳',
    tempsMin: 8,
    portions: 1,
    difficulte: 1,
    moments: ['petit-dej', 'diner'],
    tags: ['rapide', 'équilibré', 'végé'],
    ingredients: [
      { produitId: 'oeuf', quantite: 3, unite: 'piece' },
      { produitId: 'beurre', quantite: 10, unite: 'g' },
      { produitId: 'lait', quantite: 30, unite: 'ml', optionnel: true },
    ],
    etapes: ['Battre les œufs.', 'Cuire doucement au beurre en remuant.'],
    kcalPortion: 270,
    proteine: 3,
    legume: 0,
    feculent: 0,
  },
  {
    id: 'bowl-fromage-blanc',
    nom: 'Bowl fromage blanc',
    emoji: '🫐',
    tempsMin: 5,
    portions: 1,
    difficulte: 1,
    moments: ['petit-dej', 'gouter'],
    tags: ['rapide', 'équilibré', 'sucré'],
    ingredients: [
      { produitId: 'fromage-blanc', quantite: 150, unite: 'g' },
      { produitId: 'banane', quantite: 1, unite: 'piece' },
      { produitId: 'flocons-avoine', quantite: 30, unite: 'g' },
      { produitId: 'miel', quantite: 1, unite: 'cac', optionnel: true },
    ],
    etapes: ['Mélanger fromage blanc, fruits, flocons et un peu de miel.'],
    kcalPortion: 280,
    proteine: 2,
    legume: 0,
    feculent: 2,
  },
  {
    id: 'pancakes',
    nom: 'Pancakes',
    emoji: '🥞',
    tempsMin: 20,
    portions: 3,
    difficulte: 2,
    moments: ['petit-dej', 'gouter'],
    tags: ['sucré', 'enfant'],
    ingredients: [
      { produitId: 'farine', quantite: 200, unite: 'g' },
      { produitId: 'oeuf', quantite: 2, unite: 'piece' },
      { produitId: 'lait', quantite: 250, unite: 'ml' },
      { produitId: 'sucre', quantite: 30, unite: 'g' },
    ],
    etapes: ['Mélanger en pâte épaisse.', 'Cuire de petites louches à la poêle.'],
    kcalPortion: 330,
    proteine: 1,
    legume: 0,
    feculent: 3,
  },
  {
    id: 'tartine-avocat-oeuf',
    nom: 'Tartine avocat-œuf',
    emoji: '🥑',
    tempsMin: 10,
    portions: 1,
    difficulte: 1,
    moments: ['petit-dej', 'dejeuner'],
    tags: ['équilibré', 'rapide', 'végé'],
    ingredients: [
      { produitId: 'pain', quantite: 2, unite: 'piece' },
      { produitId: 'avocat', quantite: 1, unite: 'piece' },
      { produitId: 'oeuf', quantite: 1, unite: 'piece' },
    ],
    etapes: ['Écraser l’avocat sur le pain.', 'Ajouter un œuf au plat ou poché.'],
    kcalPortion: 360,
    proteine: 2,
    legume: 1,
    feculent: 2,
  },
  {
    id: 'pain-perdu',
    nom: 'Pain perdu',
    emoji: '🍮',
    tempsMin: 15,
    portions: 2,
    difficulte: 1,
    moments: ['gouter', 'petit-dej', 'dessert'],
    tags: ['sucré', 'enfant', 'réconfort'],
    ingredients: [
      { produitId: 'pain', quantite: 4, unite: 'piece' },
      { produitId: 'oeuf', quantite: 2, unite: 'piece' },
      { produitId: 'lait', quantite: 150, unite: 'ml' },
      { produitId: 'sucre', quantite: 30, unite: 'g' },
    ],
    etapes: ['Tremper le pain dans œuf+lait+sucre.', 'Dorer à la poêle beurrée.'],
    kcalPortion: 340,
    proteine: 1,
    legume: 0,
    feculent: 3,
  },

  // ===== Déjeuners / dîners =====
  {
    id: 'saumon-riz-courgette',
    nom: 'Saumon, riz et courgette',
    emoji: '🍣',
    tempsMin: 25,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner', 'diner'],
    tags: ['équilibré'],
    ingredients: [
      { produitId: 'saumon', quantite: 250, unite: 'g' },
      { produitId: 'riz', quantite: 120, unite: 'g' },
      { produitId: 'courgette', quantite: 1, unite: 'piece' },
    ],
    etapes: ['Cuire le riz.', 'Poêler la courgette.', 'Cuire le saumon 8 min.'],
    kcalPortion: 470,
    proteine: 3,
    legume: 2,
    feculent: 2,
  },
  {
    id: 'wok-nouilles',
    nom: 'Wok de nouilles aux légumes',
    emoji: '🍜',
    tempsMin: 20,
    portions: 2,
    difficulte: 2,
    moments: ['dejeuner', 'diner'],
    tags: ['asiatique', 'végé', 'rapide'],
    ingredients: [
      { produitId: 'nouilles', quantite: 200, unite: 'g' },
      { produitId: 'courgette', quantite: 1, unite: 'piece' },
      { produitId: 'carotte', quantite: 1, unite: 'piece' },
      { produitId: 'poivron', quantite: 1, unite: 'piece' },
      { produitId: 'sauce-soja', quantite: 3, unite: 'cas' },
    ],
    etapes: ['Cuire les nouilles.', 'Sauter les légumes au wok.', 'Mélanger avec la sauce soja.'],
    kcalPortion: 420,
    proteine: 1,
    legume: 3,
    feculent: 3,
  },
  {
    id: 'gnocchi-tomate-mozza',
    nom: 'Poêlée de gnocchi tomate-mozza',
    emoji: '🥔',
    tempsMin: 15,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner', 'diner'],
    tags: ['rapide', 'végé', 'enfant', 'réconfort'],
    ingredients: [
      { produitId: 'gnocchi', quantite: 400, unite: 'g' },
      { produitId: 'sauce-tomate', quantite: 200, unite: 'ml' },
      { produitId: 'mozzarella', quantite: 125, unite: 'g' },
    ],
    etapes: ['Poêler les gnocchi.', 'Ajouter la sauce tomate.', 'Parsemer de mozzarella, laisser fondre.'],
    kcalPortion: 460,
    proteine: 2,
    legume: 1,
    feculent: 3,
  },
  {
    id: 'curry-pois-chiches',
    nom: 'Curry de pois chiches',
    emoji: '🍛',
    tempsMin: 30,
    portions: 3,
    difficulte: 2,
    moments: ['dejeuner', 'diner'],
    tags: ['végé', 'épicé', 'équilibré'],
    ingredients: [
      { produitId: 'pois-chiches', quantite: 250, unite: 'g' },
      { produitId: 'sauce-tomate', quantite: 200, unite: 'ml' },
      { produitId: 'oignon', quantite: 1, unite: 'piece' },
      { produitId: 'epices', quantite: 2, unite: 'cac' },
      { produitId: 'riz', quantite: 150, unite: 'g' },
    ],
    etapes: [
      'Faire revenir l’oignon et les épices.',
      'Ajouter pois chiches et sauce tomate, mijoter 15 min.',
      'Servir avec le riz.',
    ],
    kcalPortion: 440,
    proteine: 2,
    legume: 2,
    feculent: 3,
  },
  {
    id: 'riz-saute-crevettes',
    nom: 'Riz sauté aux crevettes',
    emoji: '🍤',
    tempsMin: 20,
    portions: 2,
    difficulte: 2,
    moments: ['dejeuner', 'diner'],
    tags: ['asiatique'],
    ingredients: [
      { produitId: 'riz', quantite: 150, unite: 'g' },
      { produitId: 'crevettes', quantite: 150, unite: 'g' },
      { produitId: 'oeuf', quantite: 2, unite: 'piece' },
      { produitId: 'petit-pois', quantite: 100, unite: 'g' },
      { produitId: 'sauce-soja', quantite: 2, unite: 'cas' },
    ],
    etapes: ['Cuire le riz.', 'Sauter crevettes, œuf, petits pois.', 'Mélanger riz + sauce soja.'],
    kcalPortion: 430,
    proteine: 3,
    legume: 1,
    feculent: 3,
  },
  {
    id: 'omelette-champignons',
    nom: 'Omelette aux champignons',
    emoji: '🍄',
    tempsMin: 12,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner', 'diner'],
    tags: ['végé', 'rapide'],
    ingredients: [
      { produitId: 'oeuf', quantite: 4, unite: 'piece' },
      { produitId: 'champignon', quantite: 150, unite: 'g' },
      { produitId: 'fromage-rape', quantite: 40, unite: 'g', optionnel: true },
    ],
    etapes: ['Poêler les champignons.', 'Verser les œufs battus, plier.'],
    kcalPortion: 300,
    proteine: 3,
    legume: 1,
    feculent: 0,
  },
  {
    id: 'wrap-poulet',
    nom: 'Wrap poulet crudités',
    emoji: '🌯',
    tempsMin: 15,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner', 'diner'],
    tags: ['rapide', 'équilibré'],
    ingredients: [
      { produitId: 'tortilla', quantite: 2, unite: 'piece' },
      { produitId: 'poulet', quantite: 200, unite: 'g' },
      { produitId: 'salade', quantite: 80, unite: 'g' },
      { produitId: 'tomate', quantite: 1, unite: 'piece' },
    ],
    etapes: ['Cuire le poulet en lamelles.', 'Garnir la tortilla, rouler.'],
    kcalPortion: 410,
    proteine: 3,
    legume: 2,
    feculent: 2,
  },
  {
    id: 'salade-avocat-thon',
    nom: 'Salade avocat-thon',
    emoji: '🥑',
    tempsMin: 10,
    portions: 2,
    difficulte: 1,
    moments: ['dejeuner'],
    tags: ['équilibré', 'été', 'rapide'],
    ingredients: [
      { produitId: 'salade', quantite: 150, unite: 'g' },
      { produitId: 'avocat', quantite: 1, unite: 'piece' },
      { produitId: 'thon', quantite: 120, unite: 'g' },
      { produitId: 'mais', quantite: 100, unite: 'g' },
      { produitId: 'oeuf', quantite: 2, unite: 'piece', optionnel: true },
    ],
    etapes: ['Couper la salade et l’avocat.', 'Ajouter thon, maïs, œufs durs.'],
    kcalPortion: 350,
    proteine: 2,
    legume: 3,
    feculent: 1,
  },
  {
    id: 'gratin-courgettes',
    nom: 'Gratin de courgettes',
    emoji: '🥒',
    tempsMin: 35,
    portions: 3,
    difficulte: 2,
    moments: ['diner'],
    tags: ['végé', 'équilibré', 'réconfort'],
    ingredients: [
      { produitId: 'courgette', quantite: 3, unite: 'piece' },
      { produitId: 'creme', quantite: 150, unite: 'ml' },
      { produitId: 'fromage-rape', quantite: 80, unite: 'g' },
      { produitId: 'oeuf', quantite: 2, unite: 'piece' },
    ],
    etapes: ['Couper et précuire les courgettes.', 'Mélanger crème + œufs.', 'Four 20 min avec le fromage.'],
    kcalPortion: 320,
    proteine: 1,
    legume: 3,
    feculent: 0,
  },

  // ===== Desserts / goûters =====
  {
    id: 'mug-cake',
    nom: 'Mug cake chocolat',
    emoji: '🍫',
    tempsMin: 5,
    portions: 1,
    difficulte: 1,
    moments: ['dessert', 'gouter'],
    tags: ['sucré', 'enfant', 'rapide'],
    ingredients: [
      { produitId: 'farine', quantite: 40, unite: 'g' },
      { produitId: 'sucre', quantite: 30, unite: 'g' },
      { produitId: 'oeuf', quantite: 1, unite: 'piece' },
      { produitId: 'lait', quantite: 40, unite: 'ml' },
      { produitId: 'chocolat', quantite: 30, unite: 'g' },
    ],
    etapes: ['Mélanger le tout dans un mug.', 'Micro-ondes 1 min 30.'],
    kcalPortion: 380,
    proteine: 1,
    legume: 0,
    feculent: 3,
  },
  {
    id: 'salade-fruits',
    nom: 'Salade de fruits',
    emoji: '🍓',
    tempsMin: 8,
    portions: 2,
    difficulte: 1,
    moments: ['dessert', 'gouter'],
    tags: ['sucré', 'équilibré', 'rapide'],
    ingredients: [
      { produitId: 'pomme', quantite: 2, unite: 'piece' },
      { produitId: 'banane', quantite: 1, unite: 'piece' },
    ],
    etapes: ['Couper les fruits en morceaux.', 'Mélanger.'],
    kcalPortion: 110,
    proteine: 0,
    legume: 0,
    feculent: 1,
  },
]
